name: workshop-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - xarray
  - matplotlib
  - scipy
  - h5netcdf
  - ipykernel
  - geopandas
  - tqdm
  - contextily
  - pip
  - pip:
    - drama
